file =open('file.txt','w')
file.write("Hello world")
file.write("It is the second line\n")
file.write("It is the third line")
file = open('file.txt','r')
data = file.readlines()
print(data)
file = open('file.txt','w')
file.write("This is to check old data exist or not.")
file.close()
file = open('file.txt','r')
print(file.read())
file.close()